admin:
  build: docker
  volumes:
    - ./spring-boot-admin:/data
    - ~/.m2:/root/.m2
  ports:
    - 8761:8761
  environment:
    - spring.profiles.active=peer1
admin2:
  build: docker
  volumes:
    - ./spring-boot-admin:/data
    - ~/.m2:/root/.m2
  ports:
    - 8762:8762
  environment:
    - spring.profiles.active=peer2
#  environment:
#    - spring.profiles.active=application-peer1.properties
#web1:
#  build: spring-boot-docker-run
#  volumes:
#    - ./spring-boot-webapp-1:/data
#    - ~/.m2:/root/.m2
#  ports:
#    - 8081:8080
#  links:
#    - admin
#  command: mvn spring-boot:run -Dspring.boot.admin.client.url=http://localhost:8081
#web2:
#  build: spring-boot-docker-run
#  volumes:
#    - ./spring-boot-webapp-2:/data
#    - ~/.m2:/root/.m2
#  ports:
#    - 8082:8080
#  links:
#    - admin
#  command: mvn spring-boot:run -Dspring.boot.admin.client.url=http://localhost:8082
